# Define base docker image
image: registry.geops.de/build/stretch-node:latest

before_script:
  - eval $(ssh-agent -s)

# Define the stages of the build which will be run in sequence
stages:
  - build
  - deploy

# Define folders that are being cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build_maps:
  stage: build
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    when: on_success
    paths:
      - build/

build_maps_prod:
  stage: build
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build:prod
  artifacts:
    when: on_success
    paths:
      - build/

deploy_dev:
  stage: deploy
  dependencies:
    - build_maps
  script:
    - echo "$DEV_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -av --delete build/ wkp@wkp2.dev.trafimage.geops.ch:/var/www/wkp2.dev.trafimage.geops.ch

deploy_dev_manual:
  stage: deploy
  dependencies:
    - build_maps
  script:
    - echo "$DEV_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -av --delete build/ wkp@wkp2.dev.trafimage.geops.ch:/var/www/wkp2.dev.trafimage.geops.ch
  when: manual

deploy_stag_manual:
  stage: deploy
  dependencies:
    - build_maps
  script:
    - echo "$STAG_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -av --delete build/ wkp@wkp2.stag.trafimage.geops.ch:/var/www/wkp2.stag.trafimage.geops.ch
  when: manual

deploy_prod_manual:
  stage: deploy
  dependencies:
    - build_maps_prod
  script:
    - echo "$PROD_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -av --delete build/ wkp@wkp2.prod.trafimage.geops.ch:/var/www/wkp2.prod.trafimage.geops.ch
  when: manual
  only:
    - tags
    - master
