version: 1

update_configs:
  # Keep package.json (& lockfiles) up to date, batching pull requests weekly
   
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    
    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "gevos"
      - "edellucien"
    default_assignees:
      - "oterral"    
    default_labels:
      - "dependencies"
